### ISSUE TITLE
MOEO facility sub groups

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-facilities#401]
Previous classification used a mixture of a lookup and SQL case statements to map `program_name` to `facsubgrp`.  Which approach should we take in the refactored code?

**Comment by mgraber** [comment]
All combinations of program_name and the first element in service_taxonomy, along with a preliminary clasification.

[moeo_classification.csv](https://github.com/NYCPlanning/db-facilities/files/6423502/moeo_classification.csv)

**Comment by AmandaDoyle** [comment]
Attached is the latest version of the moeo dataset before they changed the schema.  I don't see the fields `factype` or `facsubgrp` so I'm not sure how those came into play.  There is another source for `facsubgrp` beyond the mapping between `program_name` and `facsubgrp` because `CHEMICAL DEPENDENCY` is a `facsubgrp` value for example.  Can you map the origin of the `factype` or `facsubgrp` in the `moeo_socialservicesiteloactions` source dataset?

[moeo_socialservicesitelocations_2019_11_12 (1).csv.zip](https://github.com/NYCPlanning/db-facilities/files/6427116/moeo_socialservicesitelocations_2019_11_12.1.csv.zip)

Regardless, we'll reach out to MOEO to ask how we should map the new fields to factype and facsubsgroup, and confirm that we should still be removing some records from the MOEO data since other sources are more reliable.

**Comment by mgraber** [comment]
@AmandaDoyle facsubgrp and facdomain didn't come from source data originally. They were mapped from a separate [lookup table](https://github.com/NYCPlanning/db-facilities/blob/main/facdb_build/referencetables/moeo_socialservicesiteloactions_classification.csv), using `program_name`, with what looks like patches added on in code.

**Comment by AmandaDoyle** [comment]
Got feedback from MOEO
Use the 'program_name' to assign facility type and map to a facility subgroup.  The service_taxonomy column is not required for the agencies.

So next steps are to map 'program_name' to facility type, and then remap 'program_name' to a facility subgroup, which I'm happy to help with by either doing a first pass or looking at something that's in progress

**Comment by AmandaDoyle** [comment]
[MOEO_FacDB_program_name_to_facsubgroup_MOEO_edits.xlsx](https://github.com/NYCPlanning/db-facilities/files/6469260/MOEO_FacDB_program_name_to_facsubgroup_MOEO_edits.xlsx)

Final program name to FacSubgroup classification attached
