### ISSUE TITLE
Changes to NYS OASAS facilities

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#597]
- [x] Update the agency name "NYS Office of Alcoholism and Substance Abuse Services" to "NYS Office of Addiction Services and Supports"
- [x] Update the subgroup value "Chemical Dependency" to "Substance Use Disorder Treatment Programs"
- [x] Change the "Operated by" value to the Provider name of the program

Data provider linked to [here](https://webapps.oasas.ny.gov/providerDirectory/index.cfm) to retrieve data and recommended updating data weekly.

**Comment by mbh329** [comment]
From my understanding of their ask, they want us to not only update the data weekly but also to update the map weekly so that the changes are reflected week over week? that doesn't seem possible based on our facilities database update schedule. We have to update the data manually for the nysoasas_programs in data library and a weekly update wouldn't change anything on the front end. let me know if you want to talk this through @AmandaDoyle cc @damonmcc

**Comment by AmandaDoyle** [comment]
@mbh329 Yes, they recommended updating the data in FacDB weekly.  We won't be doing this in the near term, that's why I put it as a note and not an action item, but I could have made that clearer.  Perhaps in the future we are updating FacDB more often than once a year.
